customhost = "database-2.cmfilhh3xlf8.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "s3-employee-bucket"
customregion = "us-east-1"
